// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("SkyFilter")]
[assembly: AssemblyDescriptionAttribute("Easy creation and fluent combination of Microsoft Azure table filters.")]
[assembly: AssemblyProductAttribute("SkyFilter")]
[assembly: AssemblyVersionAttribute("0.8")]
[assembly: AssemblyFileVersionAttribute("0.8")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8";
    }
}
