// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("SkyFilter.Azure")]
[assembly: AssemblyDescriptionAttribute("Easy creation and fluent combination of Microsoft Azure table filters.")]
[assembly: GuidAttribute("63221f4d-32e7-4be9-98c0-65c61ea0cf27")]
[assembly: AssemblyProductAttribute("SkyFilter.Azure")]
[assembly: AssemblyVersionAttribute("0.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0";
    }
}
